### ISSUE TITLE
not working on pojavlauncher 

### ISSUE THREAD

**Issue by htung2706** [TempleDevelopment/Temple-Client#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 5/24/24 12:45 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Temple Client (templeclient)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(DynamicTexture.java:37)
	at net.minecraft.client.renderer.texture.DynamicTexture.<init>(DynamicTexture.java:26)
	at xyz.templecheats.templeclient.features.gui.font.CFont.handleSprites(CFont.java:430)
	at xyz.templecheats.templeclient.features.gui.font.CFont.handleSprites(CFont.java:461)
	at xyz.templecheats.templeclient.features.gui.font.CFont.handleSprites(CFont.java:402)
	at xyz.templecheats.templeclient.features.gui.font.CFont.setupTexture(CFont.java:47)
	at xyz.templecheats.templeclient.features.gui.font.CFont.<init>(CFont.java:33)
	at xyz.templecheats.templeclient.features.gui.font.FontUtils.setupIcons(FontUtils.java:22)
	at xyz.templecheats.templeclient.features.gui.font.FontUtils.<clinit>(FontUtils.java:14)
	at xyz.templecheats.templeclient.features.gui.font.FontUtils$Fonts.setSize(FontUtils.java:90)
	at xyz.templecheats.templeclient.features.module.modules.client.FontSettings.getFont(FontSettings.java:41)
	at xyz.templecheats.templeclient.features.gui.font.Fonts.getFont(Fonts.java:8)
	at xyz.templecheats.templeclient.features.gui.font.Fonts.<clinit>(Fonts.java:16)
	at xyz.templecheats.templeclient.features.module.modules.client.hud.ModuleList.<init>(ModuleList.java:37)
	at xyz.templecheats.templeclient.features.module.modules.client.HUD.<init>(HUD.java:57)
	at xyz.templecheats.templeclient.manager.ModuleManager.initMods(ModuleManager.java:85)
	at xyz.templecheats.templeclient.manager.ModuleManager.<init>(ModuleManager.java:26)
	at xyz.templecheats.templeclient.TempleClient.init(TempleClient.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 1.8.0_392-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 89548248 bytes (85 MB) / 786956288 bytes (750 MB) up to 786956288 bytes (750 MB)
	JVM Flags: 3 total; -Xms840M -Xmx840M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID           | Version      | Source                        | Signature                                |
	|:----- |:------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft    | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp          | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge        | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | templeclient | 1.9.2        | templeclient-1.9.2.jar        | None                                     |

	Loaded coremods (and transformers): 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: Mali-G52
	OpenGlVendor: PojavLauncherTeam & ptitSeb
	CpuCount: 8

**Comment by Zane2b2t** [comment]
this means you don't have enough ram. i think I know the solution to prevent the excessive use of ram

**Comment by Zane2b2t** [comment]
> this means you don't have enough ram. i think I know the solution to prevent the excessive use of ram

uhm... while we do have a ram eating problem. even if it's solved. you still have only 750mb max allocated for pojav. which is not good at all
![image](https://github.com/TempleDevelopment/Temple-Client/assets/88916121/485fa476-ba9e-498d-bc3e-d365a76ec28b)

**Comment by htung2706** [comment]
> > điều này có nghĩa là bạn không có đủ ram. tôi nghĩ tôi biết giải pháp để ngăn chặn việc sử dụng quá nhiều ram
> 
> ừm... trong khi chúng ta có vấn đề về việc ăn ram. ngay cả khi nó được giải quyết. bạn vẫn chỉ được phân bổ tối đa 750mb cho pojav. điều đó không tốt chút nào ![hình ảnh](https://private-user-images.githubusercontent.com/88916121/333337501-485fa476-ba9e-498d-bc3e-d365a76ec28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MTM5MzAsIm5iZiI6MTcxNjUxMzYzMCwicGF0aCI6Ii84ODkxNjEyMS8zMzMzMzc1MDEtNDg1ZmE0NzYtYmE5ZS00OThkLWJjM2UtZDM2NWE3NmVjMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAxMjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMTJkY2M2NDA2NTVlYjM4ZjhmZTY3ZDhlMjYwNjY1ZDdmYzlkZWVlY2UzYTYyYTVkNzg3ODRkOGQ0YmU0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dYRfCpAxhOcvXTt6ytcHMFxuzOSpOqbSXwxHobNvavA)

it worked thank you
